version: '1'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./ddl_script.sql:/docker-entrypoint-initdb.d/ddl_script.sql
      - ./insert_data_script.sql:/docker-entrypoint-initdb.d/insert_data_script.sql
      - data:/var/lib/postgresql/data
      - ./synt_data:/var/lib/postgresql/data/synt_data
    ports:
      - "5432:5432"

volumes:
  data: